# Numpy

Numpy is the de facto standard for numerical arrays in
Python.

In [1]:
import numpy as np # recommended convention

In [2]:
x = np.array([1,2,3],dtype=np.float32)

In [3]:
x

array([1., 2., 3.], dtype=float32)

In [4]:
x.itemsize

4

In [5]:
np.sin(np.array([1,2,3],dtype=np.float32) )

array([0.84147096, 0.9092974 , 0.14112   ], dtype=float32)

In [6]:
from math import sin
[sin(i) for i in [1,2,3]] # list comprehension

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

Numpy arrays come in many dimensions. For example, the following shows a two-dimensional 2x3 array constructed from two conforming Python lists.

In [7]:
x=np.array([ [1,2,3],[4,5,6] ])
x.shape

(2, 3)

In [8]:
x=np.array([ [1,2,3],[4,5,6] ])

In [9]:
x[:,0] # 0th column

array([1, 4])

In [10]:
x[:,1] # 1st column

array([2, 5])

In [11]:
x[0,:] # 0th row

array([1, 2, 3])

In [12]:
x[1,:] # 1st row

array([4, 5, 6])

In [13]:
x[:,1:] # all rows, 1st thru last column

array([[2, 3],
       [5, 6]])

In [14]:
x[:,::2] # all rows, every other column

array([[1, 3],
       [4, 6]])

In [15]:
x[:,::-1] # reverse order of columns

array([[3, 2, 1],
       [6, 5, 4]])

## Numpy Arrays and Memory

In [16]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
x[:,[0,1,2,2]] # notice duplicated last dimension

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
y=x[:,[0,1,2,2]] # same as above, but do assign it to y
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
x[0,0]=999 # change element in x
x

array([[999.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [20]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
x = np.ones((3,3))

In [22]:
y = x[:2,:2] # view of upper left piece

In [23]:
x[0,0] = 999 # change value

In [24]:
x

array([[999.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [25]:
y

array([[999.,   1.],
       [  1.,   1.]])

In [26]:
x = np.arange(5) # create array
x

array([0, 1, 2, 3, 4])

In [27]:
y=x[[0,1,2]] # index by integer list to force copy
y

array([0, 1, 2])

In [28]:
z=x[:3] # slice creates view
z # note y and z have same entries

array([0, 1, 2])

In [29]:
x[0]=999 # change element of x

In [30]:
x

array([999,   1,   2,   3,   4])

In [31]:
y # note y is unaffected

array([0, 1, 2])

In [32]:
z # but z is (it's a view)

array([999,   1,   2])

In [33]:
from numpy.lib.stride_tricks import as_strided
x = np.arange(16,dtype=np.int64)
y=as_strided(x,(7,4),(16,8)) # overlapped entries
y

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]], dtype=int64)

In [34]:
x[::2]=99 # assign every other value

In [35]:
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15],
      dtype=int64)

In [36]:
y # the changes appear because y is a view

array([[99,  1, 99,  3],
       [99,  3, 99,  5],
       [99,  5, 99,  7],
       [99,  7, 99,  9],
       [99,  9, 99, 11],
       [99, 11, 99, 13],
       [99, 13, 99, 15]], dtype=int64)

In [37]:
n = 8 # number of elements
x = np.arange(n) # create array
k = 5 # desired number of rows
y = as_strided(x,(k,n-k+1),(x.itemsize,)*2)
y

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

## Numpy Matrices

In [38]:
import numpy as np
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x=np.matrix([[1],[0],[0]])
A*x

matrix([[1],
        [4],
        [7]])

In [39]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([[1],[0],[0]])
A.dot(x)

array([[1],
       [4],
       [7]])

Note that Python 3.x has a new @ notation for matrix multiplication so we can re-do the last calculation as follows:

In [40]:
A @ x

array([[1],
       [4],
       [7]])

In [41]:
A=np.ones((3,3))
type(A) # array not matrix

numpy.ndarray

In [42]:
x=np.ones((3,1)) # array not matrix
type(x) # array not matrix

numpy.ndarray

In [43]:
A*x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.matrix(A)*x # row-column multiplication

matrix([[3.],
        [3.],
        [3.]])

## Numpy Broadcasting

In [45]:
X,Y=np.meshgrid(np.arange(2),np.arange(2))
X

array([[0, 1],
       [0, 1]])

In [46]:
Y

array([[0, 0],
       [1, 1]])

In [47]:
X+Y

array([[0, 1],
       [1, 2]])

In [48]:
x = np.array([0,1])
y = np.array([0,1])

In [49]:
x

array([0, 1])

In [50]:
y

array([0, 1])

In [51]:
x + y[:,None] # add broadcast dimension

array([[0, 1],
       [1, 2]])

In [52]:
X+Y

array([[0, 1],
       [1, 2]])

In [53]:
x = np.array([0,1])
y = np.array([0,1,2])
X,Y = np.meshgrid(x,y)

In [54]:
X

array([[0, 1],
       [0, 1],
       [0, 1]])

In [55]:
Y

array([[0, 0],
       [1, 1],
       [2, 2]])

In [56]:
X+Y

array([[0, 1],
       [1, 2],
       [2, 3]])

In [57]:
x+y[:,None] # same as with meshgrid

array([[0, 1],
       [1, 2],
       [2, 3]])

In [58]:
x = np.array([0,1])
y = np.array([0,1,2])
z = np.array([0,1,2,3])
x+y[:,None]+z[:,None,None]

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6]]])